# --- Site Settings ---
url: "https://vincentmin.github.io"
baseurl: "" 
lang: en

# --- Main Info ---
title: Vincent Min
tagline: Blog
description: Blog by Vincent Min

# --- Theme & Build ---
theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag

# --- Header Navigation ---
header_pages:
  - about.md

# --- Author & Social ---
author:
  name: Vincent Min
  url: https://github.com/vincentmin

github:
  username: vincentmin

social:
  name: Vincent Min
  links:
    - https://github.com/vincentmin
    - https://www.linkedin.com/in/vincent-simon-min/

# --- Permalinks ---
permalink: /blog/:title/

# --- Excludes ---
exclude:
  - README.md